spring:
 application:
   name: rest-with-spring-boot-and-java
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java?useTimezone=true&serverTimezone=UTC
   username: root
   password: 98380439
 jpa:
   hibernate:
     ddl-auto: none
   properties:
     hibernate:
   show-sql: false
   open-in-view: false

logging:
  level:
    br.com.icaro.paixao: info
    # root: error

